name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for gh-pages action

      # Only include if you need to build your files
      # - name: Build
      #   run: |
      #     cd CoopFactoryFront
      #     npm install
      #     npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CoopFactoryFront
          force_orphan: true  # Ensures clean deployment
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'