name: Deploy Frontend

on:
  push:
    branches: [ "main" ] # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional build step (uncomment if needed)
      # - name: Build
      #   run: |
      #     cd CoopFactoryFront
      #     npm install
      #     npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'CoopFactoryFront' # Your folder containing index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2