name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      # If you need to build your frontend first:
      # - name: Install and Build
      #   run: |
      #     cd CoopFactoryFront
      #     npm install
      #     npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "CoopFactoryFront"  # Your specific folder
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2